---
#- name: copy mongod.service to systemd
#  copy:
#    src: mongod.service
#    dest: /lib/systemd/system/mongod.service
#    owner: root
#    group: root
#    mode: 0644

#- name: start mongodb service
#  shell: sudo systemctl start mongod
#  become: yes

- name: Stop Instances
  shell: "mongod -f ~/mongodb/conf.d/mongod.{{ item.name }}.conf --shutdown"
  args:
      executable: /bin/bash
  with_items: "{{ mongo_databases }}"
  register: command_result
  become: no
  ignore_errors: yes

- name: Start Instances
  shell: "mongod -f ~/mongodb/conf.d/mongod.{{ item.name }}.conf"
  args:
      executable: /bin/bash
  with_items: "{{ mongo_databases }}"
  become: no

