---
- name: Stop Instances
  shell: "mongod -f ~/mongodb/conf.d/mongod.{{ item.name }}.conf --shutdown"
  args:
      executable: /bin/bash
  with_items: "{{ mongo_databases }}"
  register: command_result
  become: no
  ignore_errors: yes

- name: Start Instances
  shell: "mongod -f ~/mongodb/conf.d/mongod.{{ item.name }}.conf"
  args:
      executable: /bin/bash
  with_items: "{{ mongo_databases }}"
  become: no

